DQA-12403: Debug clone

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,7 +14,6 @@ env:
   TOOLKIT_MOCK_REPO: ${{ secrets.TOOLKIT_MOCK_REPO }}
   GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}
 
-
 jobs:
   code-review:
     runs-on: ubuntu-latest
@@ -29,7 +28,10 @@ jobs:
           composer install --no-ansi --no-interaction
 
       - name: test-clone
-        run: git clone "$TOOLKIT_MOCK_REPO" test
+        run: |
+          git clone "$TOOLKIT_MOCK_REPO" test
+          ls -la test || echo 'fail'
+          ls -la test/api || echo 'fail'
 
       - name: PHPcs
         run: ./vendor/bin/run toolkit:test-phpcs
